import path from "node:path";

import { writeTextFile } from "./fs";
import {
  buildToolInputSchema,
  extractSecuritySchemes,
  listOpenApiOperations,
  openApiProjectMeta,
  schemaToJsonSchema,
} from "./openapi-read";
import type { OpenApiOperationRecord } from "./openapi-read";
import type { BrunogenConfig, GenerationWarning } from "./model";

export async function writeAiArtifacts(
  openApi: Record<string, unknown>,
  outputDirectory: string,
  config: BrunogenConfig,
  warnings: GenerationWarning[],
): Promise<void> {
  const operations = listOpenApiOperations(openApi);
  const meta = openApiProjectMeta(openApi);
  const securitySchemes = extractSecuritySchemes(openApi);

  await writeTextFile(
    path.join(outputDirectory, "api-context.md"),
    renderApiContextMarkdown(openApi, operations, meta, securitySchemes, config),
  );

  await writeTextFile(
    path.join(outputDirectory, "tools.json"),
    `${JSON.stringify(buildToolsDocument(operations, meta), null, 2)}\n`,
  );

  await writeTextFile(
    path.join(outputDirectory, "findings.json"),
    `${JSON.stringify(buildFindingsDocument(openApi, operations, warnings, meta), null, 2)}\n`,
  );
}

function renderApiContextMarkdown(
  openApi: Record<string, unknown>,
  operations: ReturnType<typeof listOpenApiOperations>,
  meta: ReturnType<typeof openApiProjectMeta>,
  securitySchemes: Record<string, Record<string, unknown>>,
  config: BrunogenConfig,
): string {
  const lines: string[] = [
    `# ${meta.title} API Context`,
    "",
    `Generated by [brunogen](https://github.com/ryan-prayoga/brunogen). Use this file as the source of truth for API-related AI tasks.`,
    "",
    "## Project",
    "",
    `- Name: ${meta.title}`,
    `- Version: ${meta.version}`,
    `- Base URL: ${meta.serverUrl}`,
    `- Endpoints: ${operations.length}`,
    "",
    "## Auth",
    "",
  ];

  if (Object.keys(securitySchemes).length === 0) {
    lines.push("- No auth schemes inferred. Treat endpoints as public unless source code says otherwise.");
  } else {
    for (const [name, scheme] of Object.entries(securitySchemes)) {
      lines.push(`- **${name}**: ${describeSecurityScheme(scheme, config)}`);
    }
  }

  lines.push("", "## Environments", "");
  for (const environment of config.environments) {
    lines.push(`- **${environment.name}**: ${JSON.stringify(environment.variables)}`);
  }

  lines.push("", "## Endpoints", "");

  const grouped = groupOperationsByTag(operations);
  for (const [tag, tagOperations] of grouped) {
    lines.push(`### ${tag}`, "");
    for (const operation of tagOperations) {
      lines.push(`#### ${operation.method.toUpperCase()} ${operation.pathname} — \`${operation.operationId}\``);
      lines.push("");
      lines.push(operation.summary);
      lines.push("");

      if (operation.source?.file) {
        const location = operation.source.line
          ? `${operation.source.file}:${operation.source.line}`
          : operation.source.file;
        lines.push(`- Source: \`${location}\``);
      }

      if (operation.security && operation.security.length > 0) {
        lines.push(`- Security: ${JSON.stringify(operation.security)}`);
      } else {
        lines.push("- Security: none inferred");
      }

      const pathParams = operation.parameters.filter((parameter) => parameter.in === "path");
      const queryParams = operation.parameters.filter((parameter) => parameter.in === "query");
      const headerParams = operation.parameters.filter((parameter) => parameter.in === "header");

      if (pathParams.length > 0) {
        lines.push(`- Path params: ${formatParameterList(pathParams)}`);
      }

      if (queryParams.length > 0) {
        lines.push(`- Query params: ${formatParameterList(queryParams)}`);
      }

      if (headerParams.length > 0) {
        lines.push(`- Headers: ${formatParameterList(headerParams)}`);
      }

      const requestBodySchema = operation.requestBody?.content?.["application/json"]?.schema
        ?? operation.requestBody?.content?.["application/x-www-form-urlencoded"]?.schema
        ?? operation.requestBody?.content?.["multipart/form-data"]?.schema;

      if (requestBodySchema) {
        lines.push(`- Request body: \`${JSON.stringify(schemaToJsonSchema(requestBodySchema))}\``);
      }

      if (operation.responses && Object.keys(operation.responses).length > 0) {
        const responseSummary = Object.entries(operation.responses).map(([status, response]) => {
          const schema = response.content?.["application/json"]?.schema;
          return schema
            ? `${status}: ${JSON.stringify(schemaToJsonSchema(schema))}`
            : `${status}: ${response.description ?? "response"}`;
        });
        lines.push(`- Responses: ${responseSummary.join("; ")}`);
      }

      if (operation.warnings.length > 0) {
        lines.push("- Warnings:");
        for (const warning of operation.warnings) {
          lines.push(`  - [${warning.code}] ${warning.message}`);
        }
      }

      lines.push("");
    }
  }

  lines.push("## OpenAPI", "", `- File: \`${config.output.openapiFile}\``);
  lines.push(`- Spec version: ${String(openApi.openapi ?? "3.1.0")}`);

  return `${lines.join("\n")}\n`;
}

function buildToolsDocument(
  operations: ReturnType<typeof listOpenApiOperations>,
  meta: ReturnType<typeof openApiProjectMeta>,
): Record<string, unknown> {
  return {
    schemaVersion: 1,
    provider: "brunogen",
    project: meta,
    tools: operations.map((operation) => ({
      type: "function",
      function: {
        name: operation.operationId,
        description: `${operation.method.toUpperCase()} ${operation.pathname} — ${operation.summary}`,
        parameters: buildToolInputSchema(operation),
      },
    })),
  };
}

function buildFindingsDocument(
  openApi: Record<string, unknown>,
  operations: ReturnType<typeof listOpenApiOperations>,
  warnings: GenerationWarning[],
  meta: ReturnType<typeof openApiProjectMeta>,
): Record<string, unknown> {
  const findings = [
    ...warnings.map((warning) => normalizeFinding(warning)),
    ...operations.flatMap((operation) =>
      operation.warnings.map((warning) => normalizeFinding(warning, operation)),
    ),
  ];

  const unauthenticated = operations.filter(
    (operation) => !operation.security || operation.security.length === 0,
  );

  for (const operation of unauthenticated) {
    findings.push({
      code: "UNAUTHENTICATED_ENDPOINT",
      severity: "info",
      message: "No auth requirement inferred for this endpoint.",
      endpoint: `${operation.method.toUpperCase()} ${operation.pathname}`,
      operationId: operation.operationId,
      source: operation.source,
    });
  }

  return {
    schemaVersion: 1,
    provider: "brunogen",
    generatedAt: new Date().toISOString(),
    project: meta,
    summary: {
      totalFindings: findings.length,
      endpoints: operations.length,
      unauthenticatedEndpoints: unauthenticated.length,
    },
    findings,
    openapi: {
      file: ".brunogen/openapi.yaml",
      version: String(openApi.openapi ?? "3.1.0"),
    },
  };
}

function normalizeFinding(
  warning: GenerationWarning,
  operation?: ReturnType<typeof listOpenApiOperations>[number],
): Record<string, unknown> {
  return {
    code: warning.code,
    severity: inferSeverity(warning.code),
    message: warning.message,
    endpoint: operation ? `${operation.method.toUpperCase()} ${operation.pathname}` : undefined,
    operationId: operation?.operationId,
    source: warning.location ?? operation?.source,
  };
}

function inferSeverity(code: string): "error" | "warning" | "info" {
  if (code.includes("FAILED") || code.includes("ERROR")) {
    return "error";
  }

  if (code.includes("GAP") || code.includes("DUPLICATE") || code.includes("MISSING")) {
    return "warning";
  }

  return "info";
}

function groupOperationsByTag(
  operations: ReturnType<typeof listOpenApiOperations>,
): Array<[string, ReturnType<typeof listOpenApiOperations>]> {
  const groups = new Map<string, ReturnType<typeof listOpenApiOperations>>();

  for (const operation of operations) {
    const tag = operation.tags[0] ?? "default";
    const existing = groups.get(tag) ?? [];
    existing.push(operation);
    groups.set(tag, existing);
  }

  return [...groups.entries()];
}

function formatParameterList(
  parameters: OpenApiOperationRecord["parameters"],
): string {
  return parameters
    .map((parameter) => `${parameter.name}${parameter.required ? "" : "?"}`)
    .join(", ");
}

function describeSecurityScheme(
  scheme: Record<string, unknown>,
  config: BrunogenConfig,
): string {
  if (scheme.type === "http" && scheme.scheme === "bearer") {
    return `Bearer token via variable \`${config.auth.bearerTokenVar}\``;
  }

  if (scheme.type === "http" && scheme.scheme === "basic") {
    return `Basic auth via \`${config.auth.basicUsernameVar}\` and \`${config.auth.basicPasswordVar}\``;
  }

  if (scheme.type === "apiKey") {
    return `API key \`${scheme.name}\` in ${String(scheme.in)} via variable \`${config.auth.apiKeyVar}\``;
  }

  return JSON.stringify(scheme);
}