import path from "node:path";

import { writeTextFile } from "./fs";
import {
  buildToolInputSchema,
  listOpenApiOperations,
  openApiProjectMeta,
} from "./openapi-read";
import type { BrunogenConfig } from "./model";

export async function writeMcpServer(
  openApi: Record<string, unknown>,
  outputDirectory: string,
  config: BrunogenConfig,
): Promise<void> {
  const operations = listOpenApiOperations(openApi);
  const meta = openApiProjectMeta(openApi);
  const toolDefinitions = operations.map((operation) => ({
    name: operation.operationId,
    description: `${operation.method.toUpperCase()} ${operation.pathname} — ${operation.summary}`,
    method: operation.method.toUpperCase(),
    path: operation.pathname,
    inputSchema: buildToolInputSchema(operation),
    security: operation.security ?? [],
  }));

  await writeTextFile(
    path.join(outputDirectory, "package.json"),
    `${JSON.stringify({
      name: `${sanitizePackageName(meta.title)}-mcp`,
      version: "1.0.0",
      private: true,
      type: "module",
      description: `MCP server generated by brunogen for ${meta.title}`,
      scripts: {
        start: "node src/server.js",
        dev: "node --watch src/server.js",
      },
      dependencies: {
        "@modelcontextprotocol/sdk": "^1.12.1",
        zod: "^3.24.2",
      },
      engines: {
        node: ">=20",
      },
    }, null, 2)}\n`,
  );

  await writeTextFile(
    path.join(outputDirectory, "README.md"),
    renderMcpReadme(meta, config),
  );

  await writeTextFile(
    path.join(outputDirectory, "src", "server.js"),
    renderMcpServerSource(meta, toolDefinitions, config),
  );
}

function renderMcpReadme(
  meta: ReturnType<typeof openApiProjectMeta>,
  config: BrunogenConfig,
): string {
  return `# ${meta.title} MCP Server

Generated by [brunogen](https://github.com/ryan-prayoga/brunogen).

## Setup

\`\`\`bash
cd .brunogen/mcp
npm install
\`\`\`

## Run

\`\`\`bash
BRUNOGEN_API_BASE_URL=http://localhost:8000 npm start
\`\`\`

Optional auth env vars:

- \`BRUNOGEN_BEARER_TOKEN\` for bearer auth
- \`BRUNOGEN_BASIC_USERNAME\` and \`BRUNOGEN_BASIC_PASSWORD\` for basic auth
- \`BRUNOGEN_API_KEY\` for API key auth

## Cursor / Claude Desktop

Add this server to your MCP config:

\`\`\`json
{
  "mcpServers": {
    "${sanitizePackageName(meta.title)}": {
      "command": "node",
      "args": ["${config.output.mcpDir}/src/server.js"],
      "env": {
        "BRUNOGEN_API_BASE_URL": "http://localhost:8000"
      }
    }
  }
}
\`\`\`

Regenerate with \`brunogen generate\` after API changes.
`;
}

function renderMcpServerSource(
  meta: ReturnType<typeof openApiProjectMeta>,
  toolDefinitions: Array<{
    name: string;
    description: string;
    method: string;
    path: string;
    inputSchema: Record<string, unknown>;
    security: Array<Record<string, string[]>>;
  }>,
  config: BrunogenConfig,
): string {
  const serializedTools = JSON.stringify(toolDefinitions, null, 2);

  return `import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const PROJECT = ${JSON.stringify(meta, null, 2)};
const TOOL_DEFINITIONS = ${serializedTools};
const AUTH = ${JSON.stringify({
    bearerTokenVar: config.auth.bearerTokenVar,
    basicUsernameVar: config.auth.basicUsernameVar,
    basicPasswordVar: config.auth.basicPasswordVar,
    apiKeyVar: config.auth.apiKeyVar,
    apiKeyName: config.auth.apiKeyName,
    apiKeyLocation: config.auth.apiKeyLocation,
  }, null, 2)};

const server = new McpServer({
  name: \`\${PROJECT.title}-mcp\`,
  version: PROJECT.version,
});

for (const tool of TOOL_DEFINITIONS) {
  server.tool(
    tool.name,
    tool.description,
    buildZodShape(tool.inputSchema),
    async (input) => {
      const result = await executeRequest(tool, input);
      return {
        content: [{
          type: "text",
          text: JSON.stringify(result, null, 2),
        }],
      };
    },
  );
}

async function executeRequest(tool, input) {
  const baseUrl = process.env.BRUNOGEN_API_BASE_URL ?? PROJECT.serverUrl;
  const url = new URL(resolvePath(tool.path, input), baseUrl);

  for (const [name, value] of Object.entries(input)) {
    const parameter = tool.inputSchema.properties?.[name];
    if (parameter?.description?.includes("query parameter") && value !== undefined) {
      url.searchParams.set(name, String(value));
    }
  }

  const headers = {
    Accept: "application/json",
    ...buildAuthHeaders(tool.security),
  };

  const init = {
    method: tool.method,
    headers,
  };

  if (input.body !== undefined && tool.method !== "GET" && tool.method !== "HEAD") {
    headers["Content-Type"] = "application/json";
    init.body = JSON.stringify(input.body);
  }

  const response = await fetch(url, init);
  const text = await response.text();
  let body = text;

  try {
    body = JSON.parse(text);
  } catch {
    // keep raw text
  }

  return {
    ok: response.ok,
    status: response.status,
    url: url.toString(),
    body,
  };
}

function resolvePath(pathname, input) {
  return pathname.replace(/\\{([^}]+)\\}/g, (_, name) => {
    const value = input[name];
    if (value === undefined || value === null) {
      throw new Error(\`Missing path parameter: \${name}\`);
    }
    return encodeURIComponent(String(value));
  });
}

function buildAuthHeaders(security) {
  const headers = {};

  if (!Array.isArray(security) || security.length === 0) {
    return headers;
  }

  const scheme = security[0];

  if (scheme.bearerAuth) {
    const token = process.env.BRUNOGEN_BEARER_TOKEN;
    if (token) {
      headers.Authorization = \`Bearer \${token}\`;
    }
  }

  if (scheme.basicAuth) {
    const username = process.env.BRUNOGEN_BASIC_USERNAME;
    const password = process.env.BRUNOGEN_BASIC_PASSWORD;
    if (username && password) {
      headers.Authorization = \`Basic \${Buffer.from(\`\${username}:\${password}\`).toString("base64")}\`;
    }
  }

  if (scheme.apiKeyAuth) {
    const apiKey = process.env.BRUNOGEN_API_KEY;
    if (apiKey) {
      if (AUTH.apiKeyLocation === "query") {
        return { apiKey };
      }
      headers[AUTH.apiKeyName] = apiKey;
    }
  }

  return headers;
}

function buildZodShape(inputSchema) {
  const properties = inputSchema.properties ?? {};
  const shape = {};

  for (const [name, schema] of Object.entries(properties)) {
    shape[name] = jsonSchemaToZod(schema);
  }

  return shape;
}

function jsonSchemaToZod(schema) {
  if (!schema || typeof schema !== "object") {
    return z.any().optional();
  }

  if (schema.type === "string") {
    let value = z.string();
    if (Array.isArray(schema.enum) && schema.enum.length > 0) {
      value = z.enum(schema.enum.map(String));
    }
    return schema.required ? value : value.optional();
  }

  if (schema.type === "number" || schema.type === "integer") {
    const value = z.number();
    return schema.required ? value : value.optional();
  }

  if (schema.type === "boolean") {
    const value = z.boolean();
    return schema.required ? value : value.optional();
  }

  if (schema.type === "array") {
    const value = z.array(jsonSchemaToZod(schema.items ?? { type: "string" }));
    return schema.required ? value : value.optional();
  }

  if (schema.type === "object") {
    const shape = {};
    for (const [name, property] of Object.entries(schema.properties ?? {})) {
      shape[name] = jsonSchemaToZod(property);
    }
    const value = z.object(shape);
    return schema.required ? value : value.optional();
  }

  return z.any().optional();
}

const transport = new StdioServerTransport();
await server.connect(transport);
`;
}

function sanitizePackageName(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48) || "brunogen-api";
}